### ISSUE TITLE
start-process in epc:start-server does not work on Mac OS

### ISSUE THREAD

**Issue by zuoshifan** [kiwanami/emacs-epc#23]
See
ftp://ftp.gnu.org/old-gnu/Manuals/emacs/html_chapter/emacs_36.html

**Comment by kiwanami** [comment]
Hi, @zuoshifan
The document is old. Now, those functions work in Emacs 23.x, 24.x on Mac OSX.
However, if you have any trouble, will you tell me the situation and your environment info, such as Emacs, OS and some important libraries version.

**Comment by zuoshifan** [comment]
Sorry, no trouble now.
