### ISSUE TITLE
How can I connect to existing process with specified ports?

### ISSUE THREAD

**Issue by tomoki** [kiwanami/emacs-epc#27]
Hi.

I'm currently working on EPC implementation on Scala (called Scala-elrpc).

I want to use Scala-elrpc to connect to running GUI application, but I don't know how.
Can I use `epc:start-epc-debug` or is there no way to do that?

```
(defun epc:start-epc-debug (port)
  "[internal] Return an epc:manager instance which is set up partially."
  (epc:init-epc-layer
   (make-epc:manager :server-process nil
                     :commands (cons "[DEBUG]" nil)
                     :port port
                     :connection (epc:connect "localhost" port))))
```

Thank you for your help.

**Comment by kiwanami** [comment]
Hi, @tomoki 
Your project, Scala-elrpc is great!

Well, you mean that Emacs connects to "GUI application" which is written by scala as an remote process?
If so, you can use `epc:start-epc-debug`.

1: start your GUI Application and check port number. (here, we assume the number is 9999.)
2: evaluate the function in the scratch buffer like this: `(setq epcm (epc:start-epc-debug 9999))`
3: if it succeeds, epc connects to the GUI Application and the variable `epcm` holds an epc management object.

Once a connection is established, you can use management interface `M-x epc:controller`.

Is it OK?

（あと、日本語でもOKです。）

**Comment by tomoki** [comment]
@kiwanami 
Thanks for your explanation.
I confirmed that `epc:start-epc-debug` works as I expected!

I was worried that `epc:start-epc-debug` is marked as `[internal]`.
I thought `[internal]` means that it should not be used from the other applications.

By the way, I published Scala-elrpc at https://github.com/tomoki/Scala-elrpc.
(needs more testing, documents...)
