### ISSUE TITLE
tag 0.1.1 release for melpa-stable

### ISSUE THREAD

**Issue by Valdaer** [kiwanami/emacs-epc#30]
Can you make a 0.1.1 release because latest release of emacs-edbi:  in melpa-stable http://stable.melpa.org/#/edbi depends on version 0.1.1 which isn't tagged yet in here?

It's not so huge because you can get 0.1.1 from marmalade repo but if someone wants to solely rely on melpa-stable then it can't be installed only from melpa-stable: https://github.com/kiwanami/emacs-edbi/issues/38

**Comment by kiwanami** [comment]
Hi, @Valdaer 
Thank you for your advice.
I made the tag `0.1.1` for 16e975efad63093a1f1f7b59f8fda5a3cf34f2a0.

I hope that solve the problem.
